"""
game_config.py - DeckOps game config writer

Writes display/resolution settings to each game's config file during install.
Settings are based on tuned Steam Deck configs (1280x800, 90Hz, 16:10).

Supported games:
    MW2 SP   — players/config.cfg
    MW2 MP   — players/iw4x_config.cfg
    MW3 SP   — players2/config.cfg
    BO1 SP   — players/config.cfg        (shared with ZM)
    BO1 MP   — players/config_mp.cfg
    BO2 MP   — Plutonium compatdata/202990/.../t6/players/plutonium_mp.cfg
    BO2 ZM   — Plutonium compatdata/212910/.../t6/players/plutonium_zm.cfg
    MW3 MP   — already correct, skipped

Strategy:
    If the config file already exists, patch only the keys defined here.
    If it does not exist, write a minimal config with only the display keys.
"""

import os
import re

# ── Display settings ──────────────────────────────────────────────────────────

# Keys shared by all IW-engine titles (MW2, MW3, BO1)
_IW_DISPLAY = {
    "r_mode":           "1280x800",
    "r_aspectRatio":    "wide 16:10",
    "r_displayRefresh": "90 Hz",
    "r_aaSamples":      "4",
    "r_fullscreen":     "1",
    "r_monitor":        "0",
    "r_vsync":          "0",
    "vid_xpos":         "0",
    "vid_ypos":         "0",
}

# BO2 Plutonium uses seta syntax and has slightly different key set
_BO2_DISPLAY = {
    "r_mode":        "1280x800",
    "r_aspectRatio": "wide 16:10",
    "r_aaSamples":   "4",
    "r_fullscreen":  "1",
    "r_monitor":     "0",
    "r_vsync":       "0",
    "vid_xpos":      "0",
    "vid_ypos":      "0",
}

# Per-game config specs:
#   key      → (relative_path, settings_dict, syntax)
# syntax: "set"  → seta key "value"  (Plutonium/iw4x style)
#         "set"  → set  key "value"  is NOT used — all CoD configs use seta
_GAME_CONFIGS = {
    # MW2
    "iw4sp":  ("players/config.cfg",       _IW_DISPLAY, "seta"),
    "iw4mp":  ("players/iw4x_config.cfg",  _IW_DISPLAY, "seta"),
    # MW3
    "iw5sp":  ("players2/config.cfg",      _IW_DISPLAY, "seta"),
    # iw5mp skipped — already correct
    # BO1
    "t5sp":   ("players/config.cfg",       _IW_DISPLAY, "seta"),
    "t5mp":   ("players/config_mp.cfg",    _IW_DISPLAY, "seta"),
}

# BO2 paths are absolute (inside Plutonium compatdata prefix), handled separately
_BO2_CONFIGS = {
    "t6mp": _BO2_DISPLAY,
    "t6zm": _BO2_DISPLAY,
}

# ── Core patch/write logic ────────────────────────────────────────────────────

def _patch_config(path: str, settings: dict, syntax: str = "seta"):
    """
    Patch an existing config file in-place.
    For each key in settings:
      - If the key exists in the file, replace its value.
      - If it doesn't exist, append it at the end.
    """
    with open(path, "r", errors="replace") as f:
        lines = f.readlines()

    remaining = dict(settings)  # keys still to be written

    new_lines = []
    for line in lines:
        replaced = False
        for key, value in list(remaining.items()):
            # Match:  seta key "..."  or  set key "..."
            pattern = rf'^(\s*(?:seta|set)\s+{re.escape(key)}\s+)"[^"]*"'
            if re.match(pattern, line):
                new_lines.append(f'{syntax} {key} "{value}"\n')
                del remaining[key]
                replaced = True
                break
        if not replaced:
            new_lines.append(line)

    # Append any keys that weren't found in the file
    if remaining:
        if new_lines and not new_lines[-1].endswith("\n"):
            new_lines.append("\n")
        for key, value in remaining.items():
            new_lines.append(f'{syntax} {key} "{value}"\n')

    with open(path, "w") as f:
        f.writelines(new_lines)


def _write_minimal_config(path: str, settings: dict, syntax: str = "seta"):
    """
    Write a minimal config containing only the display keys.
    Used when the config file doesn't exist yet.
    """
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write("// generated by DeckOps\n")
        for key, value in settings.items():
            f.write(f'{syntax} {key} "{value}"\n')


# ── Public API ────────────────────────────────────────────────────────────────

def write_game_configs(game_key: str, install_dir: str):
    """
    Write display config for an IW-engine game (MW2, MW3, BO1).

    game_key    — e.g. 'iw4mp', 'iw5sp', 't5mp'
    install_dir — full path to the game's install directory
    """
    if game_key not in _GAME_CONFIGS:
        return  # not a supported key (e.g. iw5mp is intentionally skipped)

    rel_path, settings, syntax = _GAME_CONFIGS[game_key]
    full_path = os.path.join(install_dir, rel_path)

    if os.path.exists(full_path):
        _patch_config(full_path, settings, syntax)
    else:
        _write_minimal_config(full_path, settings, syntax)


def write_bo2_config(game_key: str, compatdata_root: str):
    """
    Write display config for a BO2 Plutonium game.

    game_key        — 't6mp' or 't6zm'
    compatdata_root — path to ~/.local/share/Steam/steamapps/compatdata
    """
    if game_key not in _BO2_CONFIGS:
        return

    appid_map = {
        "t6mp": "202990",
        "t6zm": "212910",
    }
    filename_map = {
        "t6mp": "plutonium_mp.cfg",
        "t6zm": "plutonium_zm.cfg",
    }

    appid    = appid_map[game_key]
    filename = filename_map[game_key]
    settings = _BO2_CONFIGS[game_key]

    full_path = os.path.join(
        compatdata_root, appid,
        "pfx", "drive_c", "users", "steamuser",
        "AppData", "Local", "Plutonium", "storage", "t6", "players",
        filename,
    )

    if os.path.exists(full_path):
        _patch_config(full_path, settings, syntax="seta")
    else:
        _write_minimal_config(full_path, settings, syntax="seta")
